// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxclisripwxqathhnjfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4Y2xpc3JpcHd4cWF0aGhuamZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODk2NDUsImV4cCI6MjA1ODQ2NTY0NX0.Avvmydiftt36s8QZpA6LudrN4XY4-NUxKxSnI56kxUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);